const tones = {
  "Under contract": "neutral",
  "Lender search": "warn",
  Renovation: "good",
  "For rent": "warn",
  "For sale": "warn",
  Sold: "good",
  Exit: "warn",
  Complete: "good",
  Active: "good",
  New: "good",
  Submitted: "good",
  Approved: "good",
  Rejected: "bad",
  "Needs information": "warn",
  "Needs second approval": "warn",
  "Needs attention": "warn",
  "On track": "good",
  "Needs verification": "warn",
  Verified: "good",
  Funded: "good",
  Requested: "warn",
  Open: "warn",
  Paid: "good",
  High: "bad",
  Medium: "warn",
  Low: "neutral",
  Rented: "good",
  Queued: "neutral",
  Sending: "warn",
  Sent: "good",
  Failed: "bad",
  Draft: "neutral",
  "In progress": "good",
  "Will append": "good",
  Added: "good",
  Duplicate: "warn",
  Skipped: "neutral",
  Verify: "warn",
  Planning: "neutral",
}

export function StatusPill({ children }) {
  return <span className={`pill tone-${tones[children] || "neutral"}`}>{children}</span>
}
